version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:h1sp0stgr3s@db:5432/hispec-api
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: h1sp0stgr3s
      POSTGRES_DB: hispec-api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
