version: '3.8'

services:
  database:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: h1sp0stgr3s
      POSTGRES_DB: hispec-api
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    build: .
    environment:
      - DB_USER=admin
      - DB_PASSWORD=h1sp0stgr3s
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=hispec-api
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  postgres:
